# Comando para executar: docker compose up --build --force-recreate
version: '3.9'

networks:
  msc-network:
    driver: bridge

volumes:
  pgdata:
  rabbitmq_data:

services:
  db_postgres_hacka_msc_mgmt_media:
    container_name: db_postgres_hacka_msc_mgmt_media
    image: 'postgres:13.4'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mscmgmtmedia
    ports:
      - "5432:5432"
    networks:
      - msc-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:4-management'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - msc-network