server:
  port: ${PORT:8088}
  error:
    include-message: always
  servlet:
    context-path: '/mgmt-media/'

spring:
  application:
    name: hacka-msc-mgmt-media
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:mscmgmtmedia}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        show_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: Always
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  mvc:
    problemdetails:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

variables:
  env: ${ENV:local}
  aws:
    region: ${AWS_REGION:us-east-1}

    access-key: ${AWS_ACCESS_KEY:localstack}
    secret-key: ${AWS_SECRET_KEY:localstack}
    session-token: ${AWS_SESSION_TOKEN:localstack}

    bucket-name: ${HACKA_BUCKET_NAME_MEDIA_FILES:media-files}

    queue-name-processing: ${QUEUE_NAME_PROCESSING:processing_media}
    queue-name-result: ${QUEUE_NAME_RESULT:result_media}
