apiVersion: v1
kind: Service
metadata:
  name: hacka-msc-mgmt-media-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: hacka-msc-mgmt-media-service
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8088
      nodePort: 30007
  selector:
    app: hacka-msc-mgmt-media
