apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacka-msc-mgmt-media
  labels:
    app: hacka-msc-mgmt-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hacka-msc-mgmt-media
  template:
    metadata:
      labels:
        app: hacka-msc-mgmt-media
    spec:
      containers:
        - name: hacka-msc-mgmt-media
          image: josevitordurante/hacka-msc-mgmt-media:latest
          ports:
            - containerPort: 8088
          env:
            - name: PORT
              value: "8088"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-mgmt-media-config
                  key: DB_NAME
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-mgmt-media-config
                  key: DB_URL
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-mgmt-media-config
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-mgmt-media-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-mgmt-media-config
                  key: DB_PASSWORD
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-mgmt-media-config
                  key: ENV
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-mgmt-media-config
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-mgmt-media-config
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-mgmt-media-config
                  key: AWS_SECRET_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-mgmt-media-config
                  key: AWS_SESSION_TOKEN
            - name: QUEUE_NAME_PROCESSING
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-mgmt-media-config
                  key: QUEUE_NAME_PROCESSING
            - name: QUEUE_NAME_RESULT
              valueFrom:
                configMapKeyRef:
                  name: hacka-msc-mgmt-media-config
                  key: QUEUE_NAME_RESULT
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
